// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/webhookdelivery"
	"github.com/looplj/axonhub/internal/objects"
)

// WebhookDeliveryUpdate is the builder for updating WebhookDelivery entities.
type WebhookDeliveryUpdate struct {
	config
	hooks     []Hook
	mutation  *WebhookDeliveryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the WebhookDeliveryUpdate builder.
func (_u *WebhookDeliveryUpdate) Where(ps ...predicate.WebhookDelivery) *WebhookDeliveryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WebhookDeliveryUpdate) SetUpdatedAt(v time.Time) *WebhookDeliveryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEvent sets the "event" field.
func (_u *WebhookDeliveryUpdate) SetEvent(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetEvent(v)
	return _u
}

// SetNillableEvent sets the "event" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableEvent(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetEvent(*v)
	}
	return _u
}

// SetTargetName sets the "target_name" field.
func (_u *WebhookDeliveryUpdate) SetTargetName(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetTargetName(v)
	return _u
}

// SetNillableTargetName sets the "target_name" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableTargetName(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetTargetName(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *WebhookDeliveryUpdate) SetTargetType(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableTargetType(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *WebhookDeliveryUpdate) SetURL(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableURL(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *WebhookDeliveryUpdate) SetMethod(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableMethod(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetRequestHeaders sets the "request_headers" field.
func (_u *WebhookDeliveryUpdate) SetRequestHeaders(v []objects.HeaderEntry) *WebhookDeliveryUpdate {
	_u.mutation.SetRequestHeaders(v)
	return _u
}

// AppendRequestHeaders appends value to the "request_headers" field.
func (_u *WebhookDeliveryUpdate) AppendRequestHeaders(v []objects.HeaderEntry) *WebhookDeliveryUpdate {
	_u.mutation.AppendRequestHeaders(v)
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *WebhookDeliveryUpdate) SetRequestBody(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableRequestBody(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *WebhookDeliveryUpdate) SetStatus(v webhookdelivery.Status) *WebhookDeliveryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableStatus(v *webhookdelivery.Status) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResponseStatus sets the "response_status" field.
func (_u *WebhookDeliveryUpdate) SetResponseStatus(v int) *WebhookDeliveryUpdate {
	_u.mutation.ResetResponseStatus()
	_u.mutation.SetResponseStatus(v)
	return _u
}

// SetNillableResponseStatus sets the "response_status" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableResponseStatus(v *int) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetResponseStatus(*v)
	}
	return _u
}

// AddResponseStatus adds value to the "response_status" field.
func (_u *WebhookDeliveryUpdate) AddResponseStatus(v int) *WebhookDeliveryUpdate {
	_u.mutation.AddResponseStatus(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *WebhookDeliveryUpdate) SetErrorMessage(v string) *WebhookDeliveryUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *WebhookDeliveryUpdate) SetNillableErrorMessage(v *string) *WebhookDeliveryUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *WebhookDeliveryUpdate) ClearErrorMessage() *WebhookDeliveryUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the WebhookDeliveryMutation object of the builder.
func (_u *WebhookDeliveryUpdate) Mutation() *WebhookDeliveryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WebhookDeliveryUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebhookDeliveryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WebhookDeliveryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebhookDeliveryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WebhookDeliveryUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if webhookdelivery.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized webhookdelivery.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := webhookdelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebhookDeliveryUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := webhookdelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WebhookDelivery.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *WebhookDeliveryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WebhookDeliveryUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *WebhookDeliveryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(webhookdelivery.Table, webhookdelivery.Columns, sqlgraph.NewFieldSpec(webhookdelivery.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(webhookdelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Event(); ok {
		_spec.SetField(webhookdelivery.FieldEvent, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetName(); ok {
		_spec.SetField(webhookdelivery.FieldTargetName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(webhookdelivery.FieldTargetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(webhookdelivery.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(webhookdelivery.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHeaders(); ok {
		_spec.SetField(webhookdelivery.FieldRequestHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequestHeaders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, webhookdelivery.FieldRequestHeaders, value)
		})
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(webhookdelivery.FieldRequestBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(webhookdelivery.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResponseStatus(); ok {
		_spec.SetField(webhookdelivery.FieldResponseStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseStatus(); ok {
		_spec.AddField(webhookdelivery.FieldResponseStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(webhookdelivery.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(webhookdelivery.FieldErrorMessage, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webhookdelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WebhookDeliveryUpdateOne is the builder for updating a single WebhookDelivery entity.
type WebhookDeliveryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *WebhookDeliveryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WebhookDeliveryUpdateOne) SetUpdatedAt(v time.Time) *WebhookDeliveryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEvent sets the "event" field.
func (_u *WebhookDeliveryUpdateOne) SetEvent(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetEvent(v)
	return _u
}

// SetNillableEvent sets the "event" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableEvent(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetEvent(*v)
	}
	return _u
}

// SetTargetName sets the "target_name" field.
func (_u *WebhookDeliveryUpdateOne) SetTargetName(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetTargetName(v)
	return _u
}

// SetNillableTargetName sets the "target_name" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableTargetName(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetTargetName(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *WebhookDeliveryUpdateOne) SetTargetType(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableTargetType(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *WebhookDeliveryUpdateOne) SetURL(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableURL(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *WebhookDeliveryUpdateOne) SetMethod(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableMethod(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetRequestHeaders sets the "request_headers" field.
func (_u *WebhookDeliveryUpdateOne) SetRequestHeaders(v []objects.HeaderEntry) *WebhookDeliveryUpdateOne {
	_u.mutation.SetRequestHeaders(v)
	return _u
}

// AppendRequestHeaders appends value to the "request_headers" field.
func (_u *WebhookDeliveryUpdateOne) AppendRequestHeaders(v []objects.HeaderEntry) *WebhookDeliveryUpdateOne {
	_u.mutation.AppendRequestHeaders(v)
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *WebhookDeliveryUpdateOne) SetRequestBody(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableRequestBody(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *WebhookDeliveryUpdateOne) SetStatus(v webhookdelivery.Status) *WebhookDeliveryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableStatus(v *webhookdelivery.Status) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResponseStatus sets the "response_status" field.
func (_u *WebhookDeliveryUpdateOne) SetResponseStatus(v int) *WebhookDeliveryUpdateOne {
	_u.mutation.ResetResponseStatus()
	_u.mutation.SetResponseStatus(v)
	return _u
}

// SetNillableResponseStatus sets the "response_status" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableResponseStatus(v *int) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetResponseStatus(*v)
	}
	return _u
}

// AddResponseStatus adds value to the "response_status" field.
func (_u *WebhookDeliveryUpdateOne) AddResponseStatus(v int) *WebhookDeliveryUpdateOne {
	_u.mutation.AddResponseStatus(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *WebhookDeliveryUpdateOne) SetErrorMessage(v string) *WebhookDeliveryUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *WebhookDeliveryUpdateOne) SetNillableErrorMessage(v *string) *WebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *WebhookDeliveryUpdateOne) ClearErrorMessage() *WebhookDeliveryUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the WebhookDeliveryMutation object of the builder.
func (_u *WebhookDeliveryUpdateOne) Mutation() *WebhookDeliveryMutation {
	return _u.mutation
}

// Where appends a list predicates to the WebhookDeliveryUpdate builder.
func (_u *WebhookDeliveryUpdateOne) Where(ps ...predicate.WebhookDelivery) *WebhookDeliveryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WebhookDeliveryUpdateOne) Select(field string, fields ...string) *WebhookDeliveryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WebhookDelivery entity.
func (_u *WebhookDeliveryUpdateOne) Save(ctx context.Context) (*WebhookDelivery, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebhookDeliveryUpdateOne) SaveX(ctx context.Context) *WebhookDelivery {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WebhookDeliveryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebhookDeliveryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WebhookDeliveryUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if webhookdelivery.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized webhookdelivery.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := webhookdelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebhookDeliveryUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := webhookdelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WebhookDelivery.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *WebhookDeliveryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WebhookDeliveryUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *WebhookDeliveryUpdateOne) sqlSave(ctx context.Context) (_node *WebhookDelivery, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(webhookdelivery.Table, webhookdelivery.Columns, sqlgraph.NewFieldSpec(webhookdelivery.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WebhookDelivery.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webhookdelivery.FieldID)
		for _, f := range fields {
			if !webhookdelivery.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != webhookdelivery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(webhookdelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Event(); ok {
		_spec.SetField(webhookdelivery.FieldEvent, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetName(); ok {
		_spec.SetField(webhookdelivery.FieldTargetName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(webhookdelivery.FieldTargetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(webhookdelivery.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(webhookdelivery.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHeaders(); ok {
		_spec.SetField(webhookdelivery.FieldRequestHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequestHeaders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, webhookdelivery.FieldRequestHeaders, value)
		})
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(webhookdelivery.FieldRequestBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(webhookdelivery.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResponseStatus(); ok {
		_spec.SetField(webhookdelivery.FieldResponseStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseStatus(); ok {
		_spec.AddField(webhookdelivery.FieldResponseStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(webhookdelivery.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(webhookdelivery.FieldErrorMessage, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &WebhookDelivery{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webhookdelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
