// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/webhookdelivery"
	"github.com/looplj/axonhub/internal/objects"
)

// WebhookDeliveryCreate is the builder for creating a WebhookDelivery entity.
type WebhookDeliveryCreate struct {
	config
	mutation *WebhookDeliveryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *WebhookDeliveryCreate) SetCreatedAt(v time.Time) *WebhookDeliveryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableCreatedAt(v *time.Time) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WebhookDeliveryCreate) SetUpdatedAt(v time.Time) *WebhookDeliveryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableUpdatedAt(v *time.Time) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEvent sets the "event" field.
func (_c *WebhookDeliveryCreate) SetEvent(v string) *WebhookDeliveryCreate {
	_c.mutation.SetEvent(v)
	return _c
}

// SetTargetName sets the "target_name" field.
func (_c *WebhookDeliveryCreate) SetTargetName(v string) *WebhookDeliveryCreate {
	_c.mutation.SetTargetName(v)
	return _c
}

// SetTargetType sets the "target_type" field.
func (_c *WebhookDeliveryCreate) SetTargetType(v string) *WebhookDeliveryCreate {
	_c.mutation.SetTargetType(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *WebhookDeliveryCreate) SetURL(v string) *WebhookDeliveryCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetMethod sets the "method" field.
func (_c *WebhookDeliveryCreate) SetMethod(v string) *WebhookDeliveryCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetRequestHeaders sets the "request_headers" field.
func (_c *WebhookDeliveryCreate) SetRequestHeaders(v []objects.HeaderEntry) *WebhookDeliveryCreate {
	_c.mutation.SetRequestHeaders(v)
	return _c
}

// SetRequestBody sets the "request_body" field.
func (_c *WebhookDeliveryCreate) SetRequestBody(v string) *WebhookDeliveryCreate {
	_c.mutation.SetRequestBody(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *WebhookDeliveryCreate) SetStatus(v webhookdelivery.Status) *WebhookDeliveryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetResponseStatus sets the "response_status" field.
func (_c *WebhookDeliveryCreate) SetResponseStatus(v int) *WebhookDeliveryCreate {
	_c.mutation.SetResponseStatus(v)
	return _c
}

// SetNillableResponseStatus sets the "response_status" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableResponseStatus(v *int) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetResponseStatus(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *WebhookDeliveryCreate) SetErrorMessage(v string) *WebhookDeliveryCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableErrorMessage(v *string) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// Mutation returns the WebhookDeliveryMutation object of the builder.
func (_c *WebhookDeliveryCreate) Mutation() *WebhookDeliveryMutation {
	return _c.mutation
}

// Save creates the WebhookDelivery in the database.
func (_c *WebhookDeliveryCreate) Save(ctx context.Context) (*WebhookDelivery, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WebhookDeliveryCreate) SaveX(ctx context.Context) *WebhookDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookDeliveryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookDeliveryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WebhookDeliveryCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if webhookdelivery.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized webhookdelivery.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := webhookdelivery.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if webhookdelivery.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized webhookdelivery.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := webhookdelivery.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RequestHeaders(); !ok {
		v := webhookdelivery.DefaultRequestHeaders
		_c.mutation.SetRequestHeaders(v)
	}
	if _, ok := _c.mutation.ResponseStatus(); !ok {
		v := webhookdelivery.DefaultResponseStatus
		_c.mutation.SetResponseStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *WebhookDeliveryCreate) check() error {
	if _, ok := _c.mutation.Event(); !ok {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required field "WebhookDelivery.event"`)}
	}
	if _, ok := _c.mutation.TargetName(); !ok {
		return &ValidationError{Name: "target_name", err: errors.New(`ent: missing required field "WebhookDelivery.target_name"`)}
	}
	if _, ok := _c.mutation.TargetType(); !ok {
		return &ValidationError{Name: "target_type", err: errors.New(`ent: missing required field "WebhookDelivery.target_type"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "WebhookDelivery.url"`)}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "WebhookDelivery.method"`)}
	}
	if _, ok := _c.mutation.RequestHeaders(); !ok {
		return &ValidationError{Name: "request_headers", err: errors.New(`ent: missing required field "WebhookDelivery.request_headers"`)}
	}
	if _, ok := _c.mutation.RequestBody(); !ok {
		return &ValidationError{Name: "request_body", err: errors.New(`ent: missing required field "WebhookDelivery.request_body"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WebhookDelivery.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := webhookdelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WebhookDelivery.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResponseStatus(); !ok {
		return &ValidationError{Name: "response_status", err: errors.New(`ent: missing required field "WebhookDelivery.response_status"`)}
	}
	return nil
}

func (_c *WebhookDeliveryCreate) sqlSave(ctx context.Context) (*WebhookDelivery, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WebhookDeliveryCreate) createSpec() (*WebhookDelivery, *sqlgraph.CreateSpec) {
	var (
		_node = &WebhookDelivery{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(webhookdelivery.Table, sqlgraph.NewFieldSpec(webhookdelivery.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(webhookdelivery.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(webhookdelivery.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Event(); ok {
		_spec.SetField(webhookdelivery.FieldEvent, field.TypeString, value)
		_node.Event = value
	}
	if value, ok := _c.mutation.TargetName(); ok {
		_spec.SetField(webhookdelivery.FieldTargetName, field.TypeString, value)
		_node.TargetName = value
	}
	if value, ok := _c.mutation.TargetType(); ok {
		_spec.SetField(webhookdelivery.FieldTargetType, field.TypeString, value)
		_node.TargetType = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(webhookdelivery.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(webhookdelivery.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.RequestHeaders(); ok {
		_spec.SetField(webhookdelivery.FieldRequestHeaders, field.TypeJSON, value)
		_node.RequestHeaders = value
	}
	if value, ok := _c.mutation.RequestBody(); ok {
		_spec.SetField(webhookdelivery.FieldRequestBody, field.TypeString, value)
		_node.RequestBody = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(webhookdelivery.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ResponseStatus(); ok {
		_spec.SetField(webhookdelivery.FieldResponseStatus, field.TypeInt, value)
		_node.ResponseStatus = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(webhookdelivery.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebhookDelivery.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebhookDeliveryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WebhookDeliveryCreate) OnConflict(opts ...sql.ConflictOption) *WebhookDeliveryUpsertOne {
	_c.conflict = opts
	return &WebhookDeliveryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebhookDelivery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebhookDeliveryCreate) OnConflictColumns(columns ...string) *WebhookDeliveryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebhookDeliveryUpsertOne{
		create: _c,
	}
}

type (
	// WebhookDeliveryUpsertOne is the builder for "upsert"-ing
	//  one WebhookDelivery node.
	WebhookDeliveryUpsertOne struct {
		create *WebhookDeliveryCreate
	}

	// WebhookDeliveryUpsert is the "OnConflict" setter.
	WebhookDeliveryUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *WebhookDeliveryUpsert) SetUpdatedAt(v time.Time) *WebhookDeliveryUpsert {
	u.Set(webhookdelivery.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WebhookDeliveryUpsert) UpdateUpdatedAt() *WebhookDeliveryUpsert {
	u.SetExcluded(webhookdelivery.FieldUpdatedAt)
	return u
}

// SetEvent sets the "event" field.
func (u *WebhookDeliveryUpsert) SetEvent(v string) *WebhookDeliveryUpsert {
	u.Set(webhookdelivery.FieldEvent, v)
	return u
}

// UpdateEvent sets the "event" field to the value that was provided on create.
func (u *WebhookDeliveryUpsert) UpdateEvent() *WebhookDeliveryUpsert {
	u.SetExcluded(webhookdelivery.FieldEvent)
	return u
}

// SetTargetName sets the "target_name" field.
func (u *WebhookDeliveryUpsert) SetTargetName(v string) *WebhookDeliveryUpsert {
	u.Set(webhookdelivery.FieldTargetName, v)
	return u
}

// UpdateTargetName sets the "target_name" field to the value that was provided on create.
func (u *WebhookDeliveryUpsert) UpdateTargetName() *WebhookDeliveryUpsert {
	u.SetExcluded(webhookdelivery.FieldTargetName)
	return u
}

// SetTargetType sets the "target_type" field.
func (u *WebhookDeliveryUpsert) SetTargetType(v string) *WebhookDeliveryUpsert {
	u.Set(webhookdelivery.FieldTargetType, v)
	return u
}

// UpdateTargetType sets the "target_type" field to the value that was provided on create.
func (u *WebhookDeliveryUpsert) UpdateTargetType() *WebhookDeliveryUpsert {
	u.SetExcluded(webhookdelivery.FieldTargetType)
	return u
}

// SetURL sets the "url" field.
func (u *WebhookDeliveryUpsert) SetURL(v string) *WebhookDeliveryUpsert {
	u.Set(webhookdelivery.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *WebhookDeliveryUpsert) UpdateURL() *WebhookDeliveryUpsert {
	u.SetExcluded(webhookdelivery.FieldURL)
	return u
}

// SetMethod sets the "method" field.
func (u *WebhookDeliveryUpsert) SetMethod(v string) *WebhookDeliveryUpsert {
	u.Set(webhookdelivery.FieldMethod, v)
	return u
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *WebhookDeliveryUpsert) UpdateMethod() *WebhookDeliveryUpsert {
	u.SetExcluded(webhookdelivery.FieldMethod)
	return u
}

// SetRequestHeaders sets the "request_headers" field.
func (u *WebhookDeliveryUpsert) SetRequestHeaders(v []objects.HeaderEntry) *WebhookDeliveryUpsert {
	u.Set(webhookdelivery.FieldRequestHeaders, v)
	return u
}

// UpdateRequestHeaders sets the "request_headers" field to the value that was provided on create.
func (u *WebhookDeliveryUpsert) UpdateRequestHeaders() *WebhookDeliveryUpsert {
	u.SetExcluded(webhookdelivery.FieldRequestHeaders)
	return u
}

// SetRequestBody sets the "request_body" field.
func (u *WebhookDeliveryUpsert) SetRequestBody(v string) *WebhookDeliveryUpsert {
	u.Set(webhookdelivery.FieldRequestBody, v)
	return u
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *WebhookDeliveryUpsert) UpdateRequestBody() *WebhookDeliveryUpsert {
	u.SetExcluded(webhookdelivery.FieldRequestBody)
	return u
}

// SetStatus sets the "status" field.
func (u *WebhookDeliveryUpsert) SetStatus(v webhookdelivery.Status) *WebhookDeliveryUpsert {
	u.Set(webhookdelivery.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WebhookDeliveryUpsert) UpdateStatus() *WebhookDeliveryUpsert {
	u.SetExcluded(webhookdelivery.FieldStatus)
	return u
}

// SetResponseStatus sets the "response_status" field.
func (u *WebhookDeliveryUpsert) SetResponseStatus(v int) *WebhookDeliveryUpsert {
	u.Set(webhookdelivery.FieldResponseStatus, v)
	return u
}

// UpdateResponseStatus sets the "response_status" field to the value that was provided on create.
func (u *WebhookDeliveryUpsert) UpdateResponseStatus() *WebhookDeliveryUpsert {
	u.SetExcluded(webhookdelivery.FieldResponseStatus)
	return u
}

// AddResponseStatus adds v to the "response_status" field.
func (u *WebhookDeliveryUpsert) AddResponseStatus(v int) *WebhookDeliveryUpsert {
	u.Add(webhookdelivery.FieldResponseStatus, v)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *WebhookDeliveryUpsert) SetErrorMessage(v string) *WebhookDeliveryUpsert {
	u.Set(webhookdelivery.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *WebhookDeliveryUpsert) UpdateErrorMessage() *WebhookDeliveryUpsert {
	u.SetExcluded(webhookdelivery.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *WebhookDeliveryUpsert) ClearErrorMessage() *WebhookDeliveryUpsert {
	u.SetNull(webhookdelivery.FieldErrorMessage)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WebhookDelivery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebhookDeliveryUpsertOne) UpdateNewValues() *WebhookDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(webhookdelivery.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebhookDelivery.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WebhookDeliveryUpsertOne) Ignore() *WebhookDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebhookDeliveryUpsertOne) DoNothing() *WebhookDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebhookDeliveryCreate.OnConflict
// documentation for more info.
func (u *WebhookDeliveryUpsertOne) Update(set func(*WebhookDeliveryUpsert)) *WebhookDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebhookDeliveryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WebhookDeliveryUpsertOne) SetUpdatedAt(v time.Time) *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertOne) UpdateUpdatedAt() *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEvent sets the "event" field.
func (u *WebhookDeliveryUpsertOne) SetEvent(v string) *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetEvent(v)
	})
}

// UpdateEvent sets the "event" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertOne) UpdateEvent() *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateEvent()
	})
}

// SetTargetName sets the "target_name" field.
func (u *WebhookDeliveryUpsertOne) SetTargetName(v string) *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetTargetName(v)
	})
}

// UpdateTargetName sets the "target_name" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertOne) UpdateTargetName() *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateTargetName()
	})
}

// SetTargetType sets the "target_type" field.
func (u *WebhookDeliveryUpsertOne) SetTargetType(v string) *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetTargetType(v)
	})
}

// UpdateTargetType sets the "target_type" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertOne) UpdateTargetType() *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateTargetType()
	})
}

// SetURL sets the "url" field.
func (u *WebhookDeliveryUpsertOne) SetURL(v string) *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertOne) UpdateURL() *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateURL()
	})
}

// SetMethod sets the "method" field.
func (u *WebhookDeliveryUpsertOne) SetMethod(v string) *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertOne) UpdateMethod() *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateMethod()
	})
}

// SetRequestHeaders sets the "request_headers" field.
func (u *WebhookDeliveryUpsertOne) SetRequestHeaders(v []objects.HeaderEntry) *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetRequestHeaders(v)
	})
}

// UpdateRequestHeaders sets the "request_headers" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertOne) UpdateRequestHeaders() *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateRequestHeaders()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *WebhookDeliveryUpsertOne) SetRequestBody(v string) *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertOne) UpdateRequestBody() *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateRequestBody()
	})
}

// SetStatus sets the "status" field.
func (u *WebhookDeliveryUpsertOne) SetStatus(v webhookdelivery.Status) *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertOne) UpdateStatus() *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateStatus()
	})
}

// SetResponseStatus sets the "response_status" field.
func (u *WebhookDeliveryUpsertOne) SetResponseStatus(v int) *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetResponseStatus(v)
	})
}

// AddResponseStatus adds v to the "response_status" field.
func (u *WebhookDeliveryUpsertOne) AddResponseStatus(v int) *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.AddResponseStatus(v)
	})
}

// UpdateResponseStatus sets the "response_status" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertOne) UpdateResponseStatus() *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateResponseStatus()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *WebhookDeliveryUpsertOne) SetErrorMessage(v string) *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertOne) UpdateErrorMessage() *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *WebhookDeliveryUpsertOne) ClearErrorMessage() *WebhookDeliveryUpsertOne {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.ClearErrorMessage()
	})
}

// Exec executes the query.
func (u *WebhookDeliveryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebhookDeliveryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebhookDeliveryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WebhookDeliveryUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WebhookDeliveryUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WebhookDeliveryCreateBulk is the builder for creating many WebhookDelivery entities in bulk.
type WebhookDeliveryCreateBulk struct {
	config
	err      error
	builders []*WebhookDeliveryCreate
	conflict []sql.ConflictOption
}

// Save creates the WebhookDelivery entities in the database.
func (_c *WebhookDeliveryCreateBulk) Save(ctx context.Context) ([]*WebhookDelivery, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WebhookDelivery, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebhookDeliveryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WebhookDeliveryCreateBulk) SaveX(ctx context.Context) []*WebhookDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookDeliveryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookDeliveryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WebhookDelivery.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WebhookDeliveryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WebhookDeliveryCreateBulk) OnConflict(opts ...sql.ConflictOption) *WebhookDeliveryUpsertBulk {
	_c.conflict = opts
	return &WebhookDeliveryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WebhookDelivery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WebhookDeliveryCreateBulk) OnConflictColumns(columns ...string) *WebhookDeliveryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WebhookDeliveryUpsertBulk{
		create: _c,
	}
}

// WebhookDeliveryUpsertBulk is the builder for "upsert"-ing
// a bulk of WebhookDelivery nodes.
type WebhookDeliveryUpsertBulk struct {
	create *WebhookDeliveryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WebhookDelivery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WebhookDeliveryUpsertBulk) UpdateNewValues() *WebhookDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(webhookdelivery.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WebhookDelivery.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WebhookDeliveryUpsertBulk) Ignore() *WebhookDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WebhookDeliveryUpsertBulk) DoNothing() *WebhookDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WebhookDeliveryCreateBulk.OnConflict
// documentation for more info.
func (u *WebhookDeliveryUpsertBulk) Update(set func(*WebhookDeliveryUpsert)) *WebhookDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WebhookDeliveryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WebhookDeliveryUpsertBulk) SetUpdatedAt(v time.Time) *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertBulk) UpdateUpdatedAt() *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEvent sets the "event" field.
func (u *WebhookDeliveryUpsertBulk) SetEvent(v string) *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetEvent(v)
	})
}

// UpdateEvent sets the "event" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertBulk) UpdateEvent() *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateEvent()
	})
}

// SetTargetName sets the "target_name" field.
func (u *WebhookDeliveryUpsertBulk) SetTargetName(v string) *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetTargetName(v)
	})
}

// UpdateTargetName sets the "target_name" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertBulk) UpdateTargetName() *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateTargetName()
	})
}

// SetTargetType sets the "target_type" field.
func (u *WebhookDeliveryUpsertBulk) SetTargetType(v string) *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetTargetType(v)
	})
}

// UpdateTargetType sets the "target_type" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertBulk) UpdateTargetType() *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateTargetType()
	})
}

// SetURL sets the "url" field.
func (u *WebhookDeliveryUpsertBulk) SetURL(v string) *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertBulk) UpdateURL() *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateURL()
	})
}

// SetMethod sets the "method" field.
func (u *WebhookDeliveryUpsertBulk) SetMethod(v string) *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertBulk) UpdateMethod() *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateMethod()
	})
}

// SetRequestHeaders sets the "request_headers" field.
func (u *WebhookDeliveryUpsertBulk) SetRequestHeaders(v []objects.HeaderEntry) *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetRequestHeaders(v)
	})
}

// UpdateRequestHeaders sets the "request_headers" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertBulk) UpdateRequestHeaders() *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateRequestHeaders()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *WebhookDeliveryUpsertBulk) SetRequestBody(v string) *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertBulk) UpdateRequestBody() *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateRequestBody()
	})
}

// SetStatus sets the "status" field.
func (u *WebhookDeliveryUpsertBulk) SetStatus(v webhookdelivery.Status) *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertBulk) UpdateStatus() *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateStatus()
	})
}

// SetResponseStatus sets the "response_status" field.
func (u *WebhookDeliveryUpsertBulk) SetResponseStatus(v int) *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetResponseStatus(v)
	})
}

// AddResponseStatus adds v to the "response_status" field.
func (u *WebhookDeliveryUpsertBulk) AddResponseStatus(v int) *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.AddResponseStatus(v)
	})
}

// UpdateResponseStatus sets the "response_status" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertBulk) UpdateResponseStatus() *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateResponseStatus()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *WebhookDeliveryUpsertBulk) SetErrorMessage(v string) *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *WebhookDeliveryUpsertBulk) UpdateErrorMessage() *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *WebhookDeliveryUpsertBulk) ClearErrorMessage() *WebhookDeliveryUpsertBulk {
	return u.Update(func(s *WebhookDeliveryUpsert) {
		s.ClearErrorMessage()
	})
}

// Exec executes the query.
func (u *WebhookDeliveryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WebhookDeliveryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WebhookDeliveryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WebhookDeliveryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
