// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/webhookdelivery"
	"github.com/looplj/axonhub/internal/objects"
)

// WebhookDelivery is the model entity for the WebhookDelivery schema.
type WebhookDelivery struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Event holds the value of the "event" field.
	Event string `json:"event,omitempty"`
	// TargetName holds the value of the "target_name" field.
	TargetName string `json:"target_name,omitempty"`
	// TargetType holds the value of the "target_type" field.
	TargetType string `json:"target_type,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Method holds the value of the "method" field.
	Method string `json:"method,omitempty"`
	// RequestHeaders holds the value of the "request_headers" field.
	RequestHeaders []objects.HeaderEntry `json:"request_headers,omitempty"`
	// RequestBody holds the value of the "request_body" field.
	RequestBody string `json:"request_body,omitempty"`
	// Status holds the value of the "status" field.
	Status webhookdelivery.Status `json:"status,omitempty"`
	// ResponseStatus holds the value of the "response_status" field.
	ResponseStatus int `json:"response_status,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WebhookDelivery) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case webhookdelivery.FieldRequestHeaders:
			values[i] = new([]byte)
		case webhookdelivery.FieldID, webhookdelivery.FieldResponseStatus:
			values[i] = new(sql.NullInt64)
		case webhookdelivery.FieldEvent, webhookdelivery.FieldTargetName, webhookdelivery.FieldTargetType, webhookdelivery.FieldURL, webhookdelivery.FieldMethod, webhookdelivery.FieldRequestBody, webhookdelivery.FieldStatus, webhookdelivery.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case webhookdelivery.FieldCreatedAt, webhookdelivery.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WebhookDelivery fields.
func (_m *WebhookDelivery) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case webhookdelivery.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case webhookdelivery.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case webhookdelivery.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case webhookdelivery.FieldEvent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event", values[i])
			} else if value.Valid {
				_m.Event = value.String
			}
		case webhookdelivery.FieldTargetName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_name", values[i])
			} else if value.Valid {
				_m.TargetName = value.String
			}
		case webhookdelivery.FieldTargetType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_type", values[i])
			} else if value.Valid {
				_m.TargetType = value.String
			}
		case webhookdelivery.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case webhookdelivery.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case webhookdelivery.FieldRequestHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestHeaders); err != nil {
					return fmt.Errorf("unmarshal field request_headers: %w", err)
				}
			}
		case webhookdelivery.FieldRequestBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_body", values[i])
			} else if value.Valid {
				_m.RequestBody = value.String
			}
		case webhookdelivery.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = webhookdelivery.Status(value.String)
			}
		case webhookdelivery.FieldResponseStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_status", values[i])
			} else if value.Valid {
				_m.ResponseStatus = int(value.Int64)
			}
		case webhookdelivery.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WebhookDelivery.
// This includes values selected through modifiers, order, etc.
func (_m *WebhookDelivery) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WebhookDelivery.
// Note that you need to call WebhookDelivery.Unwrap() before calling this method if this WebhookDelivery
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WebhookDelivery) Update() *WebhookDeliveryUpdateOne {
	return NewWebhookDeliveryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WebhookDelivery entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WebhookDelivery) Unwrap() *WebhookDelivery {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WebhookDelivery is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WebhookDelivery) String() string {
	var builder strings.Builder
	builder.WriteString("WebhookDelivery(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("event=")
	builder.WriteString(_m.Event)
	builder.WriteString(", ")
	builder.WriteString("target_name=")
	builder.WriteString(_m.TargetName)
	builder.WriteString(", ")
	builder.WriteString("target_type=")
	builder.WriteString(_m.TargetType)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("request_headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestHeaders))
	builder.WriteString(", ")
	builder.WriteString("request_body=")
	builder.WriteString(_m.RequestBody)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("response_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseStatus))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteByte(')')
	return builder.String()
}

// WebhookDeliveries is a parsable slice of WebhookDelivery.
type WebhookDeliveries []*WebhookDelivery
